"""Generate pbg_tyssue/composites/*.composite.yaml from the canonical configs.

This replaces the old `get_test_*_spec()` helpers in tests/tests.py: each scenario
that used to be assembled procedurally inside a test function is emitted here as a
declarative `*.composite.yaml` spec the dashboard can discover and run directly.

The gillespie crypt parameters (rates_max / K / k / regulations / regulation_loc)
are resolved from pbg_tyssue.models.crypt_gillespie.jump_rates so the spec stays a
single source of truth with the model code rather than a hand-copied duplicate.

Run:  python scripts/gen_composites.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
OUT = ROOT / "pbg_tyssue" / "composites"
OUT.mkdir(parents=True, exist_ok=True)

# Resolve the crypt-model parameter tables straight from the model module.
from pbg_tyssue.models.crypt_gillespie import jump_rates as jr  # noqa: E402
from pbg_tyssue.models.crypt_gillespie import crypt_params as cp  # noqa: E402


# --------------------------------------------------------------------------
# Base EulerSolver configs (mirrors get_test_config / get_test_config_flat).
# bounds/output_columns/maps are empty maps (the test code passed None for
# bounds, but the config schema declares map[float]; {} is the typed no-op).
# --------------------------------------------------------------------------
def cylinder_config():
    return {
        "name": "Test Cylinder",
        "eptm": "datasets/test_cylinder.hf5",
        "tissue_type": "Sheet",
        "parameters": {
            "face_df": {
                "area_elasticity": 1.0,
                "prefered_area": 1.0,
                "perimeter_elasticity": 0.5,
                "prefered_perimeter": 3.5,
            },
            "edge_df": {"line_tension": 0.0, "is_active": 1.0},
            "vert_df": {
                "viscosity": 0.1,
                "vessel_elasticity": 1.0,
                "prefered_radius": 2.5,
                "is_alive": 1.0,
            },
        },
        "geom": "VesselGeometry",
        "effectors": ["LineTension", "FaceAreaElasticity", "PerimeterElasticity", "VesselSurfaceElasticity"],
        "ref_effector": "FaceAreaElasticity",
        "factory": "model_factory",
        "settings": {"threshold_length": 0.03},
        "auto_reconnect": True,
        "bounds": {},
        "output_columns": {},
        "maps": {},
    }


def flat_config():
    return {
        "name": "Test Square",
        "eptm": "datasets/test_square.hf5",
        "tissue_type": "Sheet",
        "parameters": {
            "face_df": {
                "area_elasticity": 1.0,
                "prefered_area": 1.0,
                "perimeter_elasticity": 0.1,
                "prefered_perimeter": 3.6,
                "migration_strength": [0.1 if i == 33 else 0.0 for i in range(206)],
                "is_alive": 1.0,
                "mx": 1.0,
                "mz": 0.0,
                "my": 1.0,
            },
            "edge_df": {"line_tension": 0.0, "is_active": 1.0},
            "vert_df": {"viscosity": 1.0, "is_alive": 1.0},
        },
        "geom": "SheetGeometry",
        "effectors": ["LineTension", "FaceAreaElasticity", "PerimeterElasticity"],
        "ref_effector": "FaceAreaElasticity",
        "factory": "model_factory_bound",
        "settings": {"threshold_length": 0.03},
        "auto_reconnect": True,
        "bounds": {},
        "output_columns": {},
        "maps": {},
    }


INTERVAL = "${interval}"


def tyssue_node(config, interval=INTERVAL):
    return {
        "_type": "process",
        "address": "local:EulerSolver",
        "config": config,
        "inputs": {"behaviors": ["Behaviors"], "global_time": ["global_time"]},
        "outputs": {
            "datasets": ["Datasets"],
            "network_changed": ["Network Changed"],
            "behaviors_update": ["Behaviors"],
        },
        "interval": interval,
    }


def base_stores():
    return {"Network Changed": False, "Behaviors": {}}


def write(name, *, description, tags, processes, state, parameters=None):
    spec = {
        "name": name,
        "description": description,
        "tags": tags,
        "requires": {"processes": processes, "types": ["tyssue_data", "behaviors"]},
        "parameters": parameters or {"interval": {"type": "float", "default": 0.1, "description": "Solver / step interval (dt)."}},
        "state": state,
    }
    path = OUT / f"{name}.composite.yaml"
    with path.open("w") as fh:
        fh.write(f"# Auto-generated by scripts/gen_composites.py — declarative replacement for\n")
        fh.write(f"# the procedural get_test_*_spec() helper in tests/tests.py.\n")
        yaml.safe_dump(spec, fh, sort_keys=False, default_flow_style=False, width=100)
    print(f"wrote {path.relative_to(ROOT)}")


# --- 1. base solver (cylinder) ------------------------------------------------
write(
    "base_solver",
    description="Baseline tyssue vertex model on a cylindrical (vessel) sheet, integrated with the "
    "generalized Euler solver. No behaviors — pure mechanical relaxation.",
    tags=["tissue", "mechanics", "geometry"],
    processes=["EulerSolver"],
    state={"Tyssue": tyssue_node(cylinder_config()), **base_stores()},
)

# --- 2. regulation (cell division) -------------------------------------------
write(
    "regulation",
    description="Cylinder sheet with a TestRegulations process that periodically triggers cell "
    "division above a critical area, driving tissue growth.",
    tags=["tissue", "mechanics", "multi-cell"],
    processes=["EulerSolver", "TestRegulations"],
    state={
        "Tyssue": tyssue_node(cylinder_config()),
        "Regulation": {
            "_type": "process",
            "address": "local:TestRegulations",
            "config": {"period": 5.0, "geom": "VesselGeometry", "crit_area": 2.0, "growth_rate": 0.2, "double": False},
            "inputs": {"global_time": ["global_time"], "datasets": ["Datasets"]},
            "outputs": {"behaviors": ["Behaviors"]},
            "interval": INTERVAL,
        },
        **base_stores(),
    },
)

# --- 3. stochastic line tension (flat sheet) ---------------------------------
def stochastic_node():
    return {
        "_type": "process",
        "address": "local:StochasticLineTension",
        "config": {"tau": 0.2, "sigma": 0.1},
        "inputs": {"datasets": ["Datasets"]},
        "outputs": {"behaviors": ["Behaviors"]},
        "interval": INTERVAL,
    }


write(
    "stochastic",
    description="Flat (square) sheet with Ornstein-Uhlenbeck stochastic line-tension fluctuations on "
    "every edge, producing jittery cell-shape dynamics / migration.",
    tags=["tissue", "mechanics"],
    processes=["EulerSolver", "StochasticLineTension"],
    state={"Tyssue": tyssue_node(flat_config()), "Stochastic": stochastic_node(), **base_stores()},
)

# --- 4. jamming (stochastic + cell jamming) ----------------------------------
write(
    "jamming",
    description="Flat sheet with stochastic line tension plus a CellJamming event that, at a trigger "
    "time, ramps preferred perimeter toward a jammed (rigid) regime.",
    tags=["tissue", "mechanics"],
    processes=["EulerSolver", "StochasticLineTension", "CellJamming"],
    state={
        "Tyssue": tyssue_node(flat_config()),
        "Stochastic": stochastic_node(),
        "Jamming": {
            "_type": "process",
            "address": "local:CellJamming",
            "config": {"trigger_time": 100.0, "rate": -0.05, "limits": [3.0, 4.2]},
            "inputs": {"global_time": ["global_time"], "datasets": ["Datasets"]},
            "outputs": {"behaviors": ["Behaviors"]},
            "interval": INTERVAL,
        },
        **base_stores(),
    },
)

# --- 5. gradient (stochastic + parameter gradient step) ----------------------
gradient_flat = flat_config()
# run_test_gradient tweaks: migration source at face 96, suppress my.
gradient_flat["parameters"]["face_df"]["migration_strength"] = [0.1 if i == 96 else 0.0 for i in range(206)]
gradient_flat["parameters"]["face_df"]["my"] = 0.0
write(
    "gradient",
    description="Flat sheet with stochastic line tension and a ParameterGradient step that imposes a "
    "linear spatial gradient of preferred perimeter along x.",
    tags=["tissue", "mechanics"],
    processes=["EulerSolver", "StochasticLineTension", "ParameterGradient"],
    state={
        "Tyssue": tyssue_node(gradient_flat),
        "Stochastic": stochastic_node(),
        "Gradient": {
            "_type": "step",
            "address": "local:ParameterGradient",
            "config": {
                "gradient_type": "linear",
                "axis": "x",
                "args": {"m": -0.1, "c": 4.6},
                "model_parameters": {"prefered_perimeter": "face"},
            },
            "inputs": {"datasets": ["Datasets"]},
            "outputs": {"behaviors": ["Behaviors"]},
        },
        **base_stores(),
    },
)

# --- 6. anisotropic tension step ---------------------------------------------
aniso_flat = flat_config()
# run_test_anisotropic overrides: factory model_factory, prefered_perimeter 3.4.
aniso_flat["factory"] = "model_factory"
aniso_flat["parameters"]["face_df"]["prefered_perimeter"] = 3.4
write(
    "anisotropic",
    description="Flat sheet with an AnisotropicTension step that biases line tension along a chosen "
    "axis, driving oriented (anisotropic) tissue elongation.",
    tags=["tissue", "mechanics"],
    processes=["EulerSolver", "AnisotropicTension"],
    state={
        "Tyssue": tyssue_node(aniso_flat),
        "Anisotropic": {
            "_type": "step",
            "address": "local:AnisotropicTension",
            "config": {"axes": ["x", "y"], "tension_values": [0.0, 0.2]},
            "inputs": {"datasets": ["Datasets"]},
            "outputs": {"behaviors": ["Behaviors"]},
        },
        **base_stores(),
    },
)

# --- 7. gillespie crypt model ------------------------------------------------
gillespie_cfg = cylinder_config()
gillespie_cfg["eptm"] = "datasets/crypt_cylinder.hf5"
gillespie_cfg["settings"].update({"radius": 2.5, "axis": "z"})
gillespie_cfg["geom"] = "VesselGeometry"
gillespie_cfg["factory"] = "model_factory_vessel"
gillespie_cfg["effectors"] = ["FaceAreaElasticity", "PerimeterElasticity", "LineTension", "VesselSurfaceElasticity"]
gillespie_cfg["parameters"]["vert_df"]["viscosity"] = 0.05
gillespie_cfg["parameters"]["vert_df"]["surface_elasticity"] = 0.1


def _floatify(obj):
    """Recursively coerce numpy scalars to plain python floats for clean YAML."""
    if isinstance(obj, dict):
        return {k: _floatify(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_floatify(v) for v in obj]
    try:
        import numpy as np

        if isinstance(obj, np.generic):
            return obj.item()
    except Exception:
        pass
    return obj


gillespie_config_block = {
    "cell_types": list(cp.cell_types),
    "rates_max": _floatify(jr.rates_max),
    "michaelis_constants": _floatify({k: v for k, v in jr.K.items() if isinstance(v, dict)}),
    "transition_lengths": _floatify(jr.k),
    "geom": "VesselGeometry",
    "global_interval": 0.005,
    "growth_rate": 0.02,
    "shrink_rate": 0.02,
    "division_crit": 1.2,
    "apoptosis_crit": 0.1,
    "regulations": _floatify(jr.regulations),
    "regulation_loc": dict(jr.regulation_loc),
}

write(
    "gillespie",
    description="Intestinal-crypt model on a cylindrical vessel: the EulerSolver handles mechanics "
    "while a Gillespie process stochastically fires cell-type transitions (stem -> progenitor -> "
    "enterocyte/goblet, extrusion) under Wnt- and density-dependent regulation.",
    tags=["tissue", "multi-cell", "cells", "kinetics"],
    processes=["EulerSolver", "Gillespie"],
    parameters={"interval": {"type": "float", "default": 0.005, "description": "Solver / Gillespie step interval (dt)."}},
    state={
        "Tyssue": tyssue_node(gillespie_cfg),
        "Gillespie": {
            "_type": "process",
            "address": "local:Gillespie",
            "config": gillespie_config_block,
            "inputs": {"datasets": ["Datasets"], "behaviors": ["Behaviors"], "global_time": ["global_time"]},
            "outputs": {"behaviors": ["Behaviors"], "gillespie_trigger": ["Gillespie Trigger"]},
            "interval": INTERVAL,
        },
        **base_stores(),
    },
)

print("\nDone — 7 composite specs written to pbg_tyssue/composites/")
